import type { PlanningEvent } from "./types";

/** Reconstructed from InventoryPlanningClient SSE logs, 2026-09-24 15:34:28. */
export const PLANNING_EVENTS: PlanningEvent[] = [
  {
    t: 0,
    event: "started",
    data: {
      runId: "c1e448d83afa40a1a2ebe61feb7b8923",
      phase: "MKE",
      operatorType: "updateOrder",
      headline: "开始规划模块二库存",
      detail:
        "本次是改单后重新分配库存。系统会依次计算需求、排列抢货顺序并分配库存。",
      summary: "本次是改单后重新分配库存。系统会依次计算需求、排列抢货顺序并分配库存。",
    },
  },
  {
    t: 17,
    event: "thinking",
    data: {
      role: "orchestrator",
      title: "规划中",
      status: "running",
      headline: "规划中",
      detail: "正在规划本阶段库存分配。",
      summary: "正在规划本阶段库存分配。",
      visible: true,
      seq: 2,
    },
  },
  {
    t: 1410,
    event: "step",
    data: {
      tool: "compute_requirements",
      title: "正在计算物料需求",
      status: "running",
      stage: "PREPARED",
      source: "",
      preview: {},
      headline: "正在计算物料需求",
      detail: "",
      summary: "正在计算物料需求",
      visible: true,
    },
  },
  {
    t: 1411,
    event: "step",
    data: {
      tool: "compute_requirements",
      title: "已算清物料需求",
      status: "done",
      stage: "REQUIREMENTS_COMPUTED",
      source: "",
      preview: { taskCount: 4 },
      headline: "已算清物料需求",
      detail: "本轮共 4 张生产任务参与分配。",
      summary: "本轮共 4 张生产任务参与分配。",
      visible: true,
    },
  },
  {
    t: 1412,
    event: "thinking",
    data: {
      role: "orchestrator",
      title: "规划中",
      status: "running",
      headline: "规划中",
      detail: "正在规划本阶段库存分配。",
      summary: "正在规划本阶段库存分配。",
      visible: true,
      seq: 2,
    },
  },
  {
    t: 3089,
    event: "step",
    data: {
      tool: "rank_tasks",
      title: "正在排列哪些订单先抢库存",
      status: "running",
      stage: "REQUIREMENTS_COMPUTED",
      source: "",
      preview: {},
      headline: "正在排列哪些订单先抢库存",
      detail: "",
      summary: "正在排列哪些订单先抢库存",
      visible: true,
    },
  },
  {
    t: 3119,
    event: "step",
    data: {
      tool: "rank_tasks",
      title: "已确定抢货顺序",
      status: "done",
      stage: "TASKS_RANKED",
      source: "default_policy",
      preview: {
        source: "default_policy",
        orderedTaskIds: [
          "2102200592612061185",
          "2102200592612061192",
          "2102200488173920001",
          "2102199933442217760",
        ],
      },
      headline: "已确定抢货顺序",
      detail: "按默认策略排出 4 张任务的抢货顺序。",
      summary: "按默认策略排出 4 张任务的抢货顺序。",
      visible: true,
    },
  },
  {
    t: 3121,
    event: "thinking",
    data: {
      role: "orchestrator",
      title: "规划中",
      status: "running",
      headline: "规划中",
      detail: "正在规划本阶段库存分配。",
      summary: "正在规划本阶段库存分配。",
      visible: true,
      seq: 2,
    },
  },
  {
    t: 4549,
    event: "step",
    data: {
      tool: "resolve_inventory_access",
      title: "正在确认专用库存给谁用",
      status: "running",
      stage: "TASKS_RANKED",
      source: "",
      preview: {},
      headline: "正在确认专用库存给谁用",
      detail: "",
      summary: "正在确认专用库存给谁用",
      visible: true,
    },
  },
  {
    t: 4551,
    event: "step",
    data: {
      tool: "resolve_inventory_access",
      title: "已确认库存可用范围",
      status: "done",
      stage: "ACCESS_RESOLVED",
      source: "default_policy",
      preview: { source: "default_policy", poolCount: 0 },
      headline: "已确认库存可用范围",
      detail: "本轮没有专用库存池，全部走共享库存。",
      summary: "本轮没有专用库存池，全部走共享库存。",
      visible: true,
    },
  },
  {
    t: 4553,
    event: "thinking",
    data: {
      role: "orchestrator",
      title: "规划中",
      status: "running",
      headline: "规划中",
      detail: "正在规划本阶段库存分配。",
      summary: "正在规划本阶段库存分配。",
      visible: true,
      seq: 2,
    },
  },
  {
    t: 5789,
    event: "step",
    data: {
      tool: "rank_demand_lines",
      title: "正在安排主料和辅料的抢货波次",
      status: "running",
      stage: "ACCESS_RESOLVED",
      source: "",
      preview: {},
      headline: "正在安排主料和辅料的抢货波次",
      detail: "",
      summary: "正在安排主料和辅料的抢货波次",
      visible: true,
    },
  },
  {
    t: 5790,
    event: "thinking",
    data: {
      role: "demand_lines.system",
      title: "正在安排主料和辅料的抢货波次",
      status: "running",
      headline: "正在安排主料和辅料的抢货波次",
      detail: "模型会把关键件放进第一波、辅料放进第二波，可能需要几秒。",
      summary: "模型会把关键件放进第一波、辅料放进第二波，可能需要几秒。",
      visible: true,
    },
  },
  {
    t: 17232,
    event: "thinking",
    data: {
      role: "demand_lines.system",
      title: "已完成主料辅料波次评估",
      status: "done",
      headline: "已完成主料辅料波次评估",
      detail:
        "关键件P3优先于P4；辅料同波次内，高改单次数(P4)得分高于低改单(P3)，符合紧急分逻辑。",
      summary:
        "关键件P3优先于P4；辅料同波次内，高改单次数(P4)得分高于低改单(P3)，符合紧急分逻辑。",
      visible: true,
    },
  },
  {
    t: 17234,
    event: "step",
    data: {
      tool: "rank_demand_lines",
      title: "已安排主料和辅料波次",
      status: "done",
      stage: "LINES_RANKED",
      source: "fallback",
      preview: { source: "fallback", lineCount: 0, waveOne: 0, waveTwo: 0 },
      headline: "已安排主料和辅料波次",
      detail: "波次评估回退到规则策略，当前没有可排列的需求行。",
      summary: "波次评估回退到规则策略，当前没有可排列的需求行。",
      visible: true,
    },
  },
  {
    t: 17241,
    event: "thinking",
    data: {
      role: "orchestrator",
      title: "规划中",
      status: "running",
      headline: "规划中",
      detail: "正在规划本阶段库存分配。",
      summary: "正在规划本阶段库存分配。",
      visible: true,
      seq: 2,
    },
  },
  {
    t: 20063,
    event: "step",
    data: {
      tool: "rank_demand_lines",
      title: "正在安排主料和辅料的抢货波次",
      status: "running",
      stage: "LINES_RANKED",
      source: "",
      preview: {},
      headline: "正在安排主料和辅料的抢货波次",
      detail: "",
      summary: "正在安排主料和辅料的抢货波次",
      visible: true,
    },
  },
  {
    t: 20068,
    event: "step",
    data: {
      tool: "rank_demand_lines",
      title: "安排主料辅料波次未完成",
      status: "error",
      stage: "LINES_RANKED",
      source: "",
      preview: {},
      headline: "安排主料辅料波次未完成",
      detail: "这一步没有做完，系统会按规则继续，或在最后给出失败原因。",
      summary: "这一步没有做完，系统会按规则继续，或在最后给出失败原因。",
      visible: true,
    },
  },
  {
    t: 20069,
    event: "thinking",
    data: {
      role: "orchestrator",
      title: "规划中",
      status: "running",
      headline: "规划中",
      detail: "正在规划本阶段库存分配。",
      summary: "正在规划本阶段库存分配。",
      visible: true,
      seq: 2,
    },
  },
  {
    t: 21304,
    event: "step",
    data: {
      tool: "resolve_inventory_access",
      title: "正在确认专用库存给谁用",
      status: "running",
      stage: "LINES_RANKED",
      source: "",
      preview: {},
      headline: "正在确认专用库存给谁用",
      detail: "",
      summary: "正在确认专用库存给谁用",
      visible: true,
    },
  },
  {
    t: 21309,
    event: "step",
    data: {
      tool: "resolve_inventory_access",
      title: "确认库存可用范围未完成",
      status: "error",
      stage: "LINES_RANKED",
      source: "",
      preview: {},
      headline: "确认库存可用范围未完成",
      detail: "这一步没有做完，系统会按规则继续，或在最后给出失败原因。",
      summary: "这一步没有做完，系统会按规则继续，或在最后给出失败原因。",
      visible: true,
    },
  },
  {
    t: 21312,
    event: "thinking",
    data: {
      role: "orchestrator",
      title: "规划中",
      status: "running",
      headline: "规划中",
      detail: "正在规划本阶段库存分配。",
      summary: "正在规划本阶段库存分配。",
      visible: true,
      seq: 2,
    },
  },
  {
    t: 22807,
    event: "step",
    data: {
      tool: "plan_upstream",
      title: "正在按顺序分配库存",
      status: "running",
      stage: "LINES_RANKED",
      source: "",
      preview: {},
      headline: "正在按顺序分配库存",
      detail: "",
      summary: "正在按顺序分配库存",
      visible: true,
    },
  },
  {
    t: 22810,
    event: "thinking",
    data: {
      role: "demand_lines.system",
      title: "正在安排主料和辅料的抢货波次",
      status: "running",
      headline: "正在安排主料和辅料的抢货波次",
      detail: "模型会把关键件放进第一波、辅料放进第二波，可能需要几秒。",
      summary: "模型会把关键件放进第一波、辅料放进第二波，可能需要几秒。",
      visible: true,
    },
  },
  {
    t: 34335,
    event: "thinking",
    data: {
      role: "demand_lines.system",
      title: "已完成主料辅料波次评估",
      status: "done",
      headline: "已完成主料辅料波次评估",
      detail:
        "关键件Wave1，辅料Wave2。同物料内按紧急度排序：P3优于P4，P4中改单多者更急。",
      summary:
        "关键件Wave1，辅料Wave2。同物料内按紧急度排序：P3优于P4，P4中改单多者更急。",
      visible: true,
    },
  },
  {
    t: 34336,
    event: "step",
    data: {
      tool: "plan_upstream",
      title: "已完成本阶段库存分配",
      status: "done",
      stage: "PURCHASE_COMPUTED",
      source: "",
      preview: {
        module1Count: 0,
        purchaseCount: 0,
        unmetCount: 0,
        module1Materials: [],
      },
      headline: "已完成本阶段库存分配",
      detail: "模块一转交 0、采购建议 0、未满足 0。",
      summary: "模块一转交 0、采购建议 0、未满足 0。",
      visible: true,
    },
  },
  {
    t: 34338,
    event: "thinking",
    data: {
      role: "orchestrator",
      title: "规划中",
      status: "running",
      headline: "规划中",
      detail: "正在规划本阶段库存分配。",
      summary: "正在规划本阶段库存分配。",
      visible: true,
      seq: 2,
    },
  },
  {
    t: 36533,
    event: "step",
    data: {
      tool: "propose_top_up",
      title: "正在评估剩余库存能否多锁一些",
      status: "running",
      stage: "PURCHASE_COMPUTED",
      source: "",
      preview: {},
      headline: "正在评估剩余库存能否多锁一些",
      detail: "",
      summary: "正在评估剩余库存能否多锁一些",
      visible: true,
    },
  },
  {
    t: 36534,
    event: "step",
    data: {
      tool: "propose_top_up",
      title: "已评估剩余库存",
      status: "done",
      stage: "TOP_UP_DONE",
      source: "none",
      preview: { source: "none", itemCount: 0 },
      headline: "已评估剩余库存",
      detail: "没有需要额外多锁的剩余库存。",
      summary: "没有需要额外多锁的剩余库存。",
      visible: true,
    },
  },
  {
    t: 36540,
    event: "thinking",
    data: {
      role: "orchestrator",
      title: "规划中",
      status: "running",
      headline: "规划中",
      detail: "正在规划本阶段库存分配。",
      summary: "正在规划本阶段库存分配。",
      visible: true,
      seq: 2,
    },
  },
  {
    t: 37847,
    event: "step",
    data: {
      tool: "get_unmet_demands",
      title: "正在查看未满足的需求",
      status: "running",
      stage: "TOP_UP_DONE",
      source: "",
      preview: {},
      headline: "正在查看未满足的需求",
      detail: "",
      summary: "正在查看未满足的需求",
      visible: true,
    },
  },
  {
    t: 37856,
    event: "step",
    data: {
      tool: "get_unmet_demands",
      title: "已查看缺口",
      status: "done",
      stage: "TOP_UP_DONE",
      source: "",
      preview: { unmetCount: 0, stage: "TOP_UP_DONE" },
      headline: "已查看缺口",
      detail: "当前还有 0 条未满足需求。",
      summary: "当前还有 0 条未满足需求。",
      visible: true,
    },
  },
  {
    t: 37858,
    event: "thinking",
    data: {
      role: "orchestrator",
      title: "规划中",
      status: "running",
      headline: "规划中",
      detail: "正在规划本阶段库存分配。",
      summary: "正在规划本阶段库存分配。",
      visible: true,
      seq: 2,
    },
  },
  {
    t: 39589,
    event: "step",
    data: {
      tool: "validate_plan",
      title: "正在校验规划结果",
      status: "running",
      stage: "TOP_UP_DONE",
      source: "",
      preview: {},
      headline: "正在校验规划结果",
      detail: "",
      summary: "正在校验规划结果",
      visible: true,
    },
  },
  {
    t: 39595,
    event: "step",
    data: {
      tool: "validate_plan",
      title: "规划结果已通过校验",
      status: "done",
      stage: "TOP_UP_DONE",
      source: "",
      preview: { passed: true, errorCount: 0 },
      headline: "规划结果已通过校验",
      detail: "数量、库存占用和冻结约束都检查通过。",
      summary: "数量、库存占用和冻结约束都检查通过。",
      visible: true,
    },
  },
  {
    t: 39606,
    event: "thinking",
    data: {
      role: "orchestrator",
      title: "规划中",
      status: "running",
      headline: "规划中",
      detail: "正在规划本阶段库存分配。",
      summary: "正在规划本阶段库存分配。",
      visible: true,
      seq: 2,
    },
  },
  {
    t: 47453,
    event: "step",
    data: {
      tool: "submit_target_plan",
      title: "正在提交本阶段规划",
      status: "running",
      stage: "TOP_UP_DONE",
      source: "",
      preview: {},
      headline: "正在提交本阶段规划",
      detail: "",
      summary: "正在提交本阶段规划",
      visible: true,
    },
  },
  {
    t: 47455,
    event: "step",
    data: {
      tool: "submit_target_plan",
      title: "本阶段规划已完成",
      status: "done",
      stage: "TOP_UP_DONE",
      source: "",
      preview: { submitted: true, runId: "c1e448d83afa40a1a2ebe61feb7b8923" },
      headline: "本阶段规划已完成",
      detail: "规划已提交，runId 已写入结果。",
      summary: "规划已提交，runId 已写入结果。",
      visible: true,
    },
  },
  {
    t: 47726,
    event: "result",
    data: {
      code: 200,
      message: "success",
      data: {
        runId: "c1e448d83afa40a1a2ebe61feb7b8923",
        actions: [],
        unmetDemands: [],
        warnings: [
          {
            code: "LINE_RANKING_FALLBACK",
            severity: "warning",
            message: "主料辅料波次评估回退到规则策略，未使用模型排序结果。",
          },
        ],
      },
    },
  },
  {
    t: 47729,
    event: "end",
    data: { eventCount: 39, status: "COMPLETED" },
  },
];

export const RUN_DURATION_MS = PLANNING_EVENTS[PLANNING_EVENTS.length - 1].t;
